name: hhsite-ci-cd

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - uses: actions/cache@v2
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts
      - name: Docusaurus build
        run: npm run build
      - name: CD into build directory and deploy the build to S3
        working-directory: ./build
        run: aws s3 sync . s3://hasibhassan.com --delete
      - name: Invalidate Cloudfront cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.dist_ID }} --paths "/*"
